# Generated by Django 6.0.1 on 2026-02-03 21:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0004_donation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='inr', max_length=10)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Donation payment',
                'verbose_name_plural': 'Donation payments',
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='payment_amount_non_negative')],
            },
        ),
    ]
