# Generated by Django 6.0.1 on 2026-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_donationpayment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Event',
                'verbose_name_plural': 'Stripe Events',
                'ordering': ['-processed_at'],
            },
        ),
    ]
