# Generated by Django 6.0.1 on 2026-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
        migrations.AddField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(related_name='donations', to='donations.category'),
        ),
    ]
