# Generated by Django 6.0.1 on 2026-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donation_category_donation_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
