# Generated by Django 6.0.1 on 2026-01-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_category_name_alter_donation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
